--liquibase formatted sql

--changeset ihar:0001-load-attempt
create table load_attempt (
    id             bigint generated by default as identity primary key,
    load_id        varchar(64)   not null,
    customer_id    varchar(64)   not null,
    amount         numeric(12,2) not null,
    load_time      timestamp     not null,
    load_date      date          not null,
    week_start     date          not null,
    accepted       boolean       not null,
    constraint uk_load_attempt_customer_load unique (customer_id, load_id)
);

create index ix_load_attempt_customer_week on load_attempt (customer_id, week_start);

create table load_attempt_violation (
    load_attempt_id bigint       not null,
    code            varchar(32)  not null,
    detail          varchar(255) not null,
    constraint pk_load_attempt_violation primary key (load_attempt_id, code),
    constraint fk_load_attempt_violation foreign key (load_attempt_id) references load_attempt (id)
);

--rollback drop table load_attempt_violation;
--rollback drop table load_attempt;
